/* eslint-disable */
// This file is automatically generated by gulp config task. IT SHOULD NOT BE MANUALLY MODIFIED!
export const config = angular.module("hybridAppSeed.config", [])
.constant("API", {"GLOBAL":{"MAX_ATTEMPTS":4},"COUNTRY":"HK","LANG":"en"});
/* eslint-enable */
